[package]
name = "our-lottery"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[features]
wasm-output-mode = [ "elrond-wasm-node",]

[dependencies.elrond-wasm]
version = "0.10.2"

[dependencies.elrond-wasm-derive]
version = "0.10.2"

[dependencies.elrond-wasm-node]
version = "0.10.2"
optional = true

[dependencies.simple-erc20]

[dev-dependencies.elrond-wasm-debug]
version = "0.10.2"
